update

diff --git a/mkjobsh b/mkjobsh
--- a/mkjobsh
+++ b/mkjobsh
@@ -13,6 +13,10 @@ minutes=0
 fs_factor=0.0
 
 for arg in $@; do
+    if [ "$arg" == "--help" ];then
+      echo $usage
+      exit 0
+    fi
     check_omp=""
     check_omp=${arg#--omp=}
     check_queue=""
@@ -68,16 +72,31 @@ for arg in $@; do
     fi
 done
 
-case $nthreads in
-    1  ) nprocs=`echo 24 \* $nnodes | bc -l` ;;
-    2  ) nprocs=`echo 12 \* $nnodes | bc -l` ;;
-    3  ) nprocs=`echo 8 \* $nnodes | bc -l` ;;
-    4  ) nprocs=`echo 6 \* $nnodes | bc -l` ;;
-    6  ) nprocs=`echo 4 \* $nnodes | bc -l` ;;
-    8  ) nprocs=`echo 3 \* $nnodes | bc -l` ;;
-    12 ) nprocs=`echo 2 \* $nnodes | bc -l` ;;
-    24 ) nprocs=`echo 1 \* $nnodes | bc -l` ;;
-    *  ) echo "Invalid input: --omp=<NUM_OPENMP> should be divisor of 24."; exit 64;; 
+case $queue in
+   "*fat" ) 
+     case "$nthreads" in
+         "1"  ) nprocs=`echo 40 \* $nnodes | bc -l` ;;
+         "2"  ) nprocs=`echo 20 \* $nnodes | bc -l` ;;
+         "4"  ) nprocs=`echo 10 \* $nnodes | bc -l` ;;
+         "5"  ) nprocs=`echo 8 \* $nnodes | bc -l` ;;
+         "8"  ) nprocs=`echo 5 \* $nnodes | bc -l` ;;
+         "10" ) nprocs=`echo 4 \* $nnodes | bc -l` ;;
+         "20" ) nprocs=`echo 2 \* $nnodes | bc -l` ;;
+         "40" ) nprocs=`echo 1 \* $nnodes | bc -l` ;;
+         *  ) echo "Invalid input: --omp=<NUM_OPENMP> should be divisor of 40."; exit 64;; 
+     esac;;
+  * )
+    case "$nthreads" in
+        "1"  ) nprocs=`echo 24 \* $nnodes | bc -l` ;;
+        "2"  ) nprocs=`echo 12 \* $nnodes | bc -l` ;;
+        "3"  ) nprocs=`echo 8 \* $nnodes | bc -l` ;;
+        "4"  ) nprocs=`echo 6 \* $nnodes | bc -l` ;;
+        "6"  ) nprocs=`echo 4 \* $nnodes | bc -l` ;;
+        "8"  ) nprocs=`echo 3 \* $nnodes | bc -l` ;;
+        "12" ) nprocs=`echo 2 \* $nnodes | bc -l` ;;
+        "24" ) nprocs=`echo 1 \* $nnodes | bc -l` ;;
+        *  ) echo "Invalid input: --omp=<NUM_OPENMP> should be divisor of 24."; exit 64;; 
+    esac;;
 esac
 
 case $queue in
diff --git a/qsh b/qsh
--- a/qsh
+++ b/qsh
@@ -34,16 +34,31 @@ for arg in $@; do
     fi
 done
 
-case $nthreads in
-    1  ) nprocs=`echo 24 \* $nnodes | bc -l` ;;
-    2  ) nprocs=`echo 12 \* $nnodes | bc -l` ;;
-    3  ) nprocs=`echo 8 \* $nnodes | bc -l` ;;
-    4  ) nprocs=`echo 6 \* $nnodes | bc -l` ;;
-    6  ) nprocs=`echo 4 \* $nnodes | bc -l` ;;
-    8  ) nprocs=`echo 3 \* $nnodes | bc -l` ;;
-    12 ) nprocs=`echo 2 \* $nnodes | bc -l` ;;
-    24 ) nprocs=`echo 1 \* $nnodes | bc -l` ;;
-    *  ) echo "Invalid input: --omp=<NUM_OPENMP> should be divisor of 24."; exit 64;; 
+case $queue in
+  "fat" )
+    case $nthreads in
+        1  ) nprocs=`echo 40 \* $nnodes | bc -l` ;;
+        2  ) nprocs=`echo 20 \* $nnodes | bc -l` ;;
+        4  ) nprocs=`echo 10 \* $nnodes | bc -l` ;;
+        5  ) nprocs=`echo 8 \* $nnodes | bc -l` ;;
+        8  ) nprocs=`echo 5 \* $nnodes | bc -l` ;;
+        10 ) nprocs=`echo 4 \* $nnodes | bc -l` ;;
+        20 ) nprocs=`echo 2 \* $nnodes | bc -l` ;;
+        40 ) nprocs=`echo 1 \* $nnodes | bc -l` ;;
+        *  ) echo "Invalid input: --omp=<NUM_OPENMP> should be divisor of 24."; exit 64;; 
+    esac;;
+  *)
+    case $nthreads in
+        1  ) nprocs=`echo 24 \* $nnodes | bc -l` ;;
+        2  ) nprocs=`echo 12 \* $nnodes | bc -l` ;;
+        3  ) nprocs=`echo 8 \* $nnodes | bc -l` ;;
+        4  ) nprocs=`echo 6 \* $nnodes | bc -l` ;;
+        6  ) nprocs=`echo 4 \* $nnodes | bc -l` ;;
+        8  ) nprocs=`echo 3 \* $nnodes | bc -l` ;;
+        12 ) nprocs=`echo 2 \* $nnodes | bc -l` ;;
+        24 ) nprocs=`echo 1 \* $nnodes | bc -l` ;;
+        *  ) echo "Invalid input: --omp=<NUM_OPENMP> should be divisor of 24."; exit 64;; 
+    esac;;
 esac
 
 case $queue in
@@ -54,7 +69,7 @@ case $queue in
 esac
 
 if [ "$dryrun" == "1" ]; then
-    echo "qsub -queue $queue -node $nnodes -mpi $nprocs -omp $nthreads -I"
+    echo "qsub -queue $queue -node $nnodes -mpi $nprocs -omp $nthreads -X -I"
 else
-    /opt/pbs/issp/bin/qsub -queue $queue -node $nnodes -mpi $nprocs -omp $nthreads -I
+    /opt/pbs/issp/bin/qsub -queue $queue -node $nnodes -mpi $nprocs -omp $nthreads -X -I 
 fi
